package com.example.joe.db;

import org.litepal.crud.DataSupport;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "tab_user_info".
 */
public class UserInfoDB extends DataSupport {

    private Object unique;//服务器返回不存入数据
    private long id;
    private String userId;
    private String username;
    private String nickName;
    private String img;
    private String phone;
    private String remark;
    private String groups;
    private int gender;
    private int badge;
    private int fans;
    private int focus;
    private int reportTimes;
    private int works;
    private int commptions;
    private int status;
    private int hot;// 1为人气王 0不是人气王
    private int collects;
    private long createTime;
    private int isCompetionWinner; // 1为擂主 0不是擂主
    private String wxAcc;
    private int userAuthType;//用户类型 加V类型  1是用户 2是企业
    private int albumNum;//专辑数
    //用户职业 英文逗号分割
    private String career;
    //融云token
    private String rongToken;
    //表示是否有直播权限 2表示有
    private int isLive;
    //设备表示号
    private String uuid;
    //渠道代码
    private String channelCode;
    //用户拼音
    private String pinYin;
    //审核状态 0:未提交审核信息,1:待审核,2:审核不通过,3:审核通过
    private int userVerified;
    // 用户名判断是否唯一,1:不唯一,即重复,0:唯一,即不重复
    private String userNameUnique;//存入数据库

    public int getUserAuthType() {
        return userAuthType;
    }

    public void setUserAuthType(int userAuthType) {
        this.userAuthType = userAuthType;
    }

    public String getWxAcc() {
        return wxAcc;
    }

    public void setWxAcc(String wxAcc) {
        this.wxAcc = wxAcc;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public int getIsCompetionWinner() {
        return isCompetionWinner;
    }

    public void setIsCompetionWinner(int isCompetionWinner) {
        this.isCompetionWinner = isCompetionWinner;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getGroups() {
        return groups;
    }

    public void setGroups(String groups) {
        this.groups = groups;
    }

    public int getGender() {
        return gender;
    }

    public void setGender(int gender) {
        this.gender = gender;
    }

    public int getBadge() {
        return badge;
    }

    public void setBadge(int badge) {
        this.badge = badge;
    }

    public int getFans() {
        return fans;
    }

    public void setFans(int fans) {
        this.fans = fans;
    }

    public int getFocus() {
        return focus;
    }

    public void setFocus(int focus) {
        this.focus = focus;
    }

    public int getReportTimes() {
        return reportTimes;
    }

    public void setReportTimes(int reportTimes) {
        this.reportTimes = reportTimes;
    }

    public int getWorks() {
        return works;
    }

    public void setWorks(int works) {
        this.works = works;
    }

    public int getCommptions() {
        return commptions;
    }

    public void setCommptions(int commptions) {
        this.commptions = commptions;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getHot() {
        return hot;
    }

    public void setHot(int hot) {
        this.hot = hot;
    }

    public int getCollects() {
        return collects;
    }

    public void setCollects(int collects) {
        this.collects = collects;
    }

    public long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(long createTime) {
        this.createTime = createTime;
    }

    public String getCareer() {
        return career;
    }

    public void setCareer(String career) {
        this.career = career;
    }

    public int getAlbumNum() {
        return albumNum;
    }

    public void setAlbumNum(int albumNum) {
        this.albumNum = albumNum;
    }

    public String getRongToken() {
        return rongToken;
    }

    public void setRongToken(String rongToken) {
        this.rongToken = rongToken;
    }

    public int getIsLive() {
        return isLive;
    }

    public void setIsLive(int isLive) {
        this.isLive = isLive;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getChannelCode() {
        return channelCode;
    }

    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode;
    }

    public String getPinYin() {
        return pinYin;
    }

    public void setPinYin(String pinYin) {
        this.pinYin = pinYin;
    }

    public Object getUnique() {
        return this.userNameUnique;
    }

    public void setUnique(Object unique) {
        this.unique = unique;
        if (null != unique)
            this.userNameUnique = unique.toString();
    }

    public int getUserVerified() {
        return userVerified;
    }

    public void setUserVerified(int userVerified) {
        this.userVerified = userVerified;
    }

    public String getUserNameUnique() {
        return userNameUnique;
    }

    public void setUserNameUnique(String userNameUnique) {
        if (null != unique)
            this.userNameUnique = unique.toString();
    }
}
